### ISSUE TITLE
Speakers page is bugged

### ISSUE THREAD

**Issue by saarthakchats** [TEDxYouthJPIS/2018_DevBuild#1]
<img width="1366" alt="screenshot 2018-11-26 at 9 37 59 pm" src="https://user-images.githubusercontent.com/24372680/49026318-91b0cd00-f1c3-11e8-8898-c4f57e00f591.png">
@kartikeya23 You made this, please fix
@NirbhaySingh2711 Take a look

**Comment by kartikeya23** [comment]
bug has been removed;
we  made a new page

**Comment by kartikeya23** [comment]
pull kar gadhe @saarthakchats
